---
# tasks file for tomcat
- name: install tomcat
  yum: name=tomcat state=present
- name: start tomcat
  service: name=tomcat state=started
- name: deploy war file
  get_url: url=https://tomcat.apache.org/tomcat-7.0-doc/appdev/sample/sample.war dest=/opt/tomcat/webapps
  notify: restart tomcat


